version: "3.8"

services:
  api:
    build:
      context: .
    container_name: online_shop_api_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14
    container_name: online_shop_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: online_shop_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always

volumes:
  postgres_data:
